Repository ucsb-cs156-s21/proj-mapache-search, pull requests merged in 2020-12, with the labels that each got.

#63 7pmc - Replaced Slack Ids with real names in the message display
  javascript/src/main/components/ChannelMessages/MessageList.js
  javascript/src/main/pages/Channels/ChannelPage.js
  javascript/src/test/components/ChannelMessages/MessageList.test.js
  javascript/src/test/pages/Channels/ChannelPage.test.js
  src/main/java/edu/ucsb/mapache/documents/SlackUser.java
Labels: f20-7pm-c

#62 7pm c link to search page
  javascript/src/main/components/Nav/AppNavbar.js
Labels: f20-7pm-c

#53 7pm b slack bot update admin page
  javascript/.env
  javascript/src/main/App.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/pages/Admin/Teams.js
  javascript/src/test/pages/Admin/Teams.test.js
  package-lock.json
  pom.xml
  src/main/java/edu/ucsb/mapache/config/SecurityConfig.java
  src/main/java/edu/ucsb/mapache/controllers/SlackSlashCommandController.java
  src/main/java/edu/ucsb/mapache/models/SlackSlashCommandParams.java
  src/main/resources/application.properties
  src/test/java/edu/ucsb/mapache/controllers/SlackSlashCommandControllerTests.java
  src/test/java/edu/ucsb/mapache/models/SlackSlashCommandParamsTests.java
Labels: f20-7pm-b

#83 AL - Fix misspelled words
  src/test/java/edu/ucsb/mapache/controllers/ChannelsControllerTests.java
Labels: staff-PR

#84 7pm-d - removed Search under Channels in the App Navbar and add app.google.search.apiToken
  README.md
  javascript/src/main/components/Nav/AppNavbar.js
  secrets-heroku.properties.SAMPLE
  secrets-localhost.properties.SAMPLE
Labels: FIX ME, f20-7pm-d

#80 7pm-a-CountMessages:As a user I can see a table that contains all slack users and their message counts so that I can see how much each participant is participating in the slack
  javascript/src/main/App.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/components/UserMessages/UserMessageList.js
  javascript/src/main/pages/AnalyzeMessageData/AnalyzeReactions.js
  javascript/src/main/pages/AnalyzeMessageData/CountMessagesByUser.js
  javascript/src/main/pages/AnalyzeMessageData/HistogramOfMessagesByUser.js
  javascript/src/main/pages/AnalyzeMessageData/SearchMessagesByUser.js
  javascript/src/main/utils/aggregateUserMessageCount.js
  javascript/src/test/components/UserMessages/UserMessageList.test.js
  javascript/src/test/pages/AnalyzeMessageData/AnalyzeReactions.test.js
  javascript/src/test/pages/AnalyzeMessageData/CountMessagesByUser.test.js
  javascript/src/test/pages/AnalyzeMessageData/HistogramOfMessagesByUser.test.js
  javascript/src/test/pages/AnalyzeMessageData/SearchMessagesByUser.test.js
  pom.xml
  src/main/java/edu/ucsb/mapache/controllers/MessagesController.java
  src/main/java/edu/ucsb/mapache/documents/Message.java
  src/main/java/edu/ucsb/mapache/repositories/MessageRepository.java
  src/test/java/edu/ucsb/mapache/controllers/MessagesControllerTests.java
  src/test/java/edu/ucsb/mapache/documents/MessageTests.java
Labels: FIX ME-please respond to code review, f20-7pm-a

#90 7pm b /mapache slack bot for Google Search
  javascript/src/main/components/ChannelMessages/MessageListView.js
  pom.xml
  secrets-heroku.properties.SAMPLE
  secrets-localhost.properties.SAMPLE
  src/main/java/edu/ucsb/mapache/controllers/SlackSlashCommandController.java
  src/main/java/edu/ucsb/mapache/models/SlackSlashCommandParams.java
  src/test/java/edu/ucsb/mapache/controllers/SlackSlashCommandControllerTests.java
  src/test/java/edu/ucsb/mapache/models/SlackSlashCommandParamsTests.java
Labels: FIX ME-please respond to code review, f20-7pm-b

#82 7pm-a-MessagesPerChannel: Searching messages by user will now also display all the channels they've participated in and how many messages they've sent per channel
  javascript/src/main/App.js
  javascript/src/main/components/UserMessages/UserChannelMessageList.js
  javascript/src/main/pages/AnalyzeMessageData/SearchMessagesByUser.js
  javascript/src/test/components/UserMessages/UserChannelMessageList.test.js
  javascript/src/test/components/UserMessages/UserMessageList.test.js
Labels: 40, f20-7pm-a

#91 7pm b student csvcrud combined
  javascript/src/main/App.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/components/Students/StudentForm.js
  javascript/src/main/components/Students/StudentTable.js
  javascript/src/main/pages/Admin/Admin.js
  javascript/src/main/pages/Students/EditStudent.js
  javascript/src/main/pages/Students/NewStudent.js
  javascript/src/main/pages/Students/StudentCSVButton.js
  javascript/src/main/pages/Students/Students.js
  javascript/src/main/services/StudentServices.js
  javascript/src/test/components/Students/StudentForm.test.js
  javascript/src/test/pages/Students/EditStudent.test.js
  javascript/src/test/pages/Students/NewStudent.test.js
  javascript/src/test/pages/Students/StudentCSVButton.test.js
  javascript/src/test/pages/Students/Students.test.js
  javascript/src/test/services/StudentServices.test.js
  package-lock.json
  pom.xml
  src/main/java/edu/ucsb/mapache/controllers/StudentController.java
  src/main/java/edu/ucsb/mapache/entities/Student.java
  src/main/java/edu/ucsb/mapache/repositories/StudentRepository.java
  src/main/java/edu/ucsb/mapache/services/CSVToObjectService.java
  src/main/java/edu/ucsb/mapache/services/CSVToObjectServiceImpl.java
  src/test/java/edu/ucsb/mapache/controllers/StudentControllerTests.java
  src/test/java/edu/ucsb/mapache/entities/StudentTests.java
  students.csv
Labels: f20-7pm-b

#86 7pm-a-MessageReaction Searching Messages by Reaction will now display user, the test and the count of that reaction for the message. #35
  javascript/src/main/App.js
  javascript/src/main/components/ChannelMessageReaction/MessageTableReaction.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/pages/AnalyzeMessageData/AnalyzeReactions.js
  javascript/src/test/components/ChannelMessageReaction/MessageTableReaction.test.js
  javascript/src/test/pages/AnalyzeMessageData/AnalyzeReactions.test.js
  src/main/java/edu/ucsb/mapache/controllers/MessagesController.java
  src/main/java/edu/ucsb/mapache/controllers/SlackUserController.java
  src/main/java/edu/ucsb/mapache/documents/Message.java
  src/main/java/edu/ucsb/mapache/documents/MessageReactions.java
  src/main/java/edu/ucsb/mapache/repositories/MessageRepository.java
  src/test/java/edu/ucsb/mapache/controllers/ChannelsControllerTests.java
  src/test/java/edu/ucsb/mapache/controllers/MessagesControllerTests.java
  src/test/java/edu/ucsb/mapache/controllers/SlackUserControllerTest.java
  src/test/java/edu/ucsb/mapache/documents/MessageReactionsTests.java
  src/test/java/edu/ucsb/mapache/documents/MessageTests.java
Labels: 40, TEAM DONE, f20-7pm-a
