Repository ucsb-cs156-s21/proj-mapache-search, pull requests merged in 2021-05, with the labels that each got.

#237 7pm-3 - nt and km - bugfix - channel mentions in list view will redirect in list view
  javascript/src/main/components/ChannelMessages/MessageListView.js
  javascript/src/test/components/ChannelMessages/MessageList.test.js
Labels: s21-7pm-3

#242 eo/bz - removed API token column from Maintain Admins page
  javascript/src/main/pages/Admin/Admin.js
Labels: S21-7pm-1-Slack-Data

#243 s21-7pm-4 kk - added logo that is visible on every page
  javascript/public/navbarlogo.png
  javascript/src/main/App.css
  javascript/src/main/components/Nav/AppNavbar.js
Labels: s21-7pm-4

#239 7pm-3 md and bl Fix enter key refreshing page on SearchMessagesByUser
  javascript/src/main/pages/AnalyzeMessageData/SearchMessagesByUser.js
Labels: s21-7pm-3

#248 7pm 4 add logo to navbar
  javascript/src/main/components/Nav/AppNavbar.js
Labels: S21-7pm-4-Admin

#241 NW/VS - 7pm-4 - Replaced old favicon logo with a new one
  javascript/public/index.html
  javascript/public/magnifyingglass-favicon.png
Labels: S21-7pm-4-Admin, s21-7pm-4

#246 7pm-1 added user API token to search info page
  javascript/src/main/pages/Admin/SearchInfo.js
Labels: S21-7pm-1-Slack-Data

#250 7pm 4 footer message
  javascript/src/main/App.css
  javascript/src/main/App.js
  javascript/src/main/components/Footer/AppFooter.js
  javascript/src/test/components/Footer/AppFooter.test.js
Labels: S21-7pm-4-Admin, s21-7pm-4

#240 7pm-3 at and jc - Fixed SearchByUser error when you are admin but not member
  src/main/java/edu/ucsb/mapache/controllers/MessagesController.java
  src/test/java/edu/ucsb/mapache/controllers/MessagesControllerTests.java
Labels: FIX ME-Team CR missing, s21-7pm-3

#245 7pm-2 Align submit button with search input box on search tab of Google search page.
  javascript/src/main/pages/Search/Search.js
Labels: FIX ME-Team CR missing, S21-7pm-2-Google-Search

#247 7pm 2 update sortcarets
  javascript/.storybook/preview.js
  javascript/src/index.js
  javascript/src/main/components/ChannelMessageReaction/MessageTableReaction.js
  javascript/src/main/components/Channels/ChannelTable.js
  javascript/src/main/components/Students/StudentTable.js
  javascript/src/main/components/UserMessages/UserChannelMessageList.js
  javascript/src/main/components/UserMessages/UserMessageList.js
  javascript/src/test/components/Channels/ChannelTable.test.js
Labels: FIX ME-Team CR missing, S21-7pm-2-Google-Search

#252 7pm-3 md and bl - Search bars on slack search
  javascript/src/main/components/ChannelMessages/MessageListView.js
  javascript/src/main/pages/Messages/SearchResults.js
  javascript/src/stories/components/ChannelMessages/MessageListView.stories.js
  javascript/src/test/components/ChannelMessages/MessageList.test.js
Labels: S21-7pm-3-Message-Display

#261 7pm-3 md - ci: Add Danger Checks for PR Issues
  .github/workflows/contribution-requirements.yml
  dangerfile.js
Labels: S21-7pm-3-Message-Display

#263 7pm-3 md - Add swagger-ui/index.html and api/docs endpoints
  pom.xml
  src/main/java/edu/ucsb/mapache/config/SecurityConfig.java
  src/main/java/edu/ucsb/mapache/config/SpringFoxConfig.java
  src/main/java/edu/ucsb/mapache/controllers/ReactController.java
  src/main/resources/application.properties
Labels: S21-7pm-3-Message-Display

#238 7pm-2 - migrate about page to home page
  javascript/src/main/App.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/pages/About/About.js
  javascript/src/main/pages/Home/Home.js
  javascript/src/stories/pages/About.stories.js
  javascript/src/test/pages/About/About.test.js
  javascript/src/test/pages/Home/Home.test.js
Labels: S21-7pm-2-Google-Search

#256 7pm-4 nw - Adds roles "Member" and "Guest" to the Admin Panel in order to differentiate non-admin users based on their membership to the Slack workspace
  javascript/src/main/pages/Admin/Admin.js
  javascript/src/test/pages/Admin/Admin.test.js
Labels: Ready for Staff Review, S21-7pm-4-Admin

#265 7pm-4 kk - Added slack bot command /mapache teamlist
  src/main/java/edu/ucsb/mapache/controllers/SlackSlashCommandController.java
  src/main/java/edu/ucsb/mapache/services/TeamListService.java
  src/test/java/edu/ucsb/mapache/controllers/SlackSlashCommandControllerTests.java
  src/test/java/edu/ucsb/mapache/services/TeamListServiceTests.java
Labels: Ready for Staff Review, S21-7pm-4-Admin

#267 7pm-2 add toast support
  javascript/package-lock.json
  javascript/package.json
  javascript/src/index.js
Labels: S21-7pm-2-Google-Search

#262 7pm-3 md - Add fixtures file to avoid hard coding in stories
  javascript/package.json
  javascript/src/fixtures/MessageFixtures.js
  javascript/src/stories/components/ChannelMessages/MessageListView.stories.js
Labels: FIX ME-please respond to code review, S21-7pm-3-Message-Display

#283 7pm-4 nw - Adds `/api/slackAdmins` endpoint that returns a list of `SlackUser`s who are Slack admins
  src/main/java/edu/ucsb/mapache/controllers/SlackUserController.java
  src/main/java/edu/ucsb/mapache/repositories/SlackUserRepository.java
  src/test/java/edu/ucsb/mapache/controllers/SlackUserControllerTest.java
Labels: Ready for Staff Review, S21-7pm-4-Admin

#272 7pm-3 md, bl, and jc - tagged user display
  javascript/src/main/App.css
  javascript/src/main/components/ChannelMessages/MessageListView.js
  javascript/src/main/components/ChannelMessages/MessageScrollableView.js
  javascript/src/test/components/ChannelMessages/MessageList.test.js
  javascript/src/test/components/ChannelMessages/MessageScrollable.test.js
  src/main/java/edu/ucsb/mapache/controllers/SlackUserController.java
  src/test/java/edu/ucsb/mapache/controllers/SlackUserControllerTest.java
Labels: S21-7pm-3-Message-Display

#284 Import from slack
  python/importFromSlack/.gitignore
  python/importFromSlack/README.md
  python/importFromSlack/requirements.txt
  python/importFromSlack/upload_archive.py
Labels: Ready for Staff Review, staff-PR

#291 7pm 1 Histogram Table
  javascript/src/main/pages/AnalyzeMessageData/HistogramOfMessagesByUser.js
  javascript/src/test/pages/AnalyzeMessageData/HistogramOfMessagesByUser.test.js
Labels: S21-7pm-1-Slack-Data

#274 7pm-2-ShowSearchQuota
  javascript/src/main/pages/Search/Search.js
  javascript/src/test/pages/Search/Search.test.js
Labels: 10, S21-7pm-2-Google-Search

#266 7pm-1 sc - Show Meaningful User Info on Analyze Reactions Page
  javascript/src/main/components/ChannelMessageReaction/MessageTableReaction.js
  javascript/src/test/components/ChannelMessageReaction/MessageTableReaction.test.js
  javascript/src/test/pages/AnalyzeMessageData/AnalyzeReactions.test.js
Labels: S21-7pm-1-Slack-Data

#280 7pm 1 mapache slack messages
  src/main/java/edu/ucsb/mapache/controllers/SlackSlashCommandController.java
  src/main/java/edu/ucsb/mapache/repositories/MessageRepository.java
  src/main/java/edu/ucsb/mapache/repositories/SlackUserRepository.java
  src/test/java/edu/ucsb/mapache/controllers/SlackSlashCommandControllerTests.java
Labels: S21-7pm-1-Slack-Data

#271 7pm-2 Show error message when trying to perform Google search without API token. #231
  javascript/src/main/pages/Search/Search.js
  javascript/src/test/pages/Search/Search.test.js
Labels: S21-7pm-2-Google-Search

#294 7pm-1 - Clean up 'search messages by user' page
  javascript/src/main/components/UserMessages/UserMessageList.js
  javascript/src/test/components/UserMessages/UserMessageList.test.js
  javascript/src/test/pages/AnalyzeMessageData/SearchMessagesByUser.test.js
Labels: Ready for Staff Review, S21-7pm-1-Slack-Data

#303 Create database entities and repository class for per user search history
  src/main/java/edu/ucsb/mapache/entities/UserSearch.java
  src/main/java/edu/ucsb/mapache/repositories/UserSearchRepository.java
  src/main/java/edu/ucsb/mapache/services/GoogleSearchService.java
Labels: S21-7pm-2-Google-Search

#290 7pm-3 search messages between two dates
  javascript/src/main/App.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/pages/AnalyzeMessageData/SearchBetweenDates.js
  javascript/src/test/pages/AnalyzeMessageData/SearchBetweenDate.test.js
  src/main/java/edu/ucsb/mapache/controllers/MessagesController.java
  src/main/java/edu/ucsb/mapache/repositories/MessageRepository.java
  src/test/java/edu/ucsb/mapache/controllers/MessagesControllerTests.java
Labels: S21-7pm-3-Message-Display

#285 7pm-4 kk /mapache whois username
  src/main/java/edu/ucsb/mapache/controllers/SlackSlashCommandController.java
  src/main/java/edu/ucsb/mapache/repositories/SlackUserRepository.java
  src/main/java/edu/ucsb/mapache/repositories/StudentRepository.java
  src/main/java/edu/ucsb/mapache/services/WhoIsService.java
  src/test/java/edu/ucsb/mapache/controllers/SlackSlashCommandControllerTests.java
  src/test/java/edu/ucsb/mapache/services/WhoIsServiceTests.java
Labels: Ready for Staff Review, S21-7pm-4-Admin
