Repository ucsb-cs156-s21/proj-mapache-search, pull requests merged in 2021-03, with the labels that each got.

#143 Use ant instead of maven to copy secrets
  pom.xml
Labels: staff-PR

#140 6pm 2 message links
  javascript/src/main/components/ChannelMessages/MessageScrollableView.js
  javascript/src/test/components/ChannelMessages/MessageScrollable.test.js
Labels: 10, w21-6pm-2

#151 6pm 2 channel topic links
  javascript/src/main/components/Channels/ChannelTable.js
  javascript/src/test/components/Channels/ChannelTable.test.js
Labels: 10, w21-6pm-2

#150 6pm 2 navbar hover
  javascript/package.json
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/components/Nav/NavbarHover.js
  javascript/src/test/components/Nav/NavbarHover.test.js
Labels: 10, w21-6pm-2

#119 7pm 2 Add an About page that recreate the original mapache search About page
  javascript/src/main/pages/About/About.js
  javascript/src/stories/pages/About.stories.js
  javascript/src/test/pages/About/About.test.js
Labels: w21-7pm-2

#153 6pm-2-messageTimeStamp
  javascript/src/main/components/ChannelMessages/time.js
  javascript/src/test/components/ChannelMessages/MessageScrollable.test.js
Labels: 5, w21-6pm-2

#141 7pm 2 Slack "/mapache teamlist <teamname>" command
  src/main/java/edu/ucsb/mapache/controllers/SlackSlashCommandController.java
  src/main/java/edu/ucsb/mapache/repositories/StudentRepository.java
  src/main/java/edu/ucsb/mapache/services/TeamEmailListService.java
  src/test/java/edu/ucsb/mapache/controllers/SlackSlashCommandControllerTests.java
  src/test/java/edu/ucsb/mapache/services/TeamEmailListServiceTests.java
Labels: FIX ME-please respond to code review, w21-7pm-2

#133 Finished tasks for making navbar collapsible
  javascript/src/main/components/Nav/AppNavbar.js
Labels: FIX ME-Team CR missing, w21-7pm-2

#124 7pm-2 Making search title more descriptive on NavBar
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/test/components/Nav/AppNavbar.test.js
Labels: FIX ME-please respond to code review, w21-7pm-2

#160 ak - created a SearchCard component to help with formatting a search …
  javascript/package-lock.json
  javascript/src/main/components/SearchCard/SearchCard.js
  javascript/src/stories/components/SearchCard/SearchCard.stories.js
  javascript/src/test/components/SearchCard/SearchCard.test.js
Labels: FIX ME-Team CR missing, W21-GoogleSearch, w21-6pm-4

#161 6pm 4 new database table
  src/main/java/edu/ucsb/mapache/entities/Search.java
  src/main/java/edu/ucsb/mapache/repositories/SearchRepository.java
  src/test/java/edu/ucsb/mapache/entities/SearchTests.java
Labels: 10, w21-6pm-4

#185 jl - Update jest timezone so timestamp related tests pass locally
  javascript/jest-TZ-setup.js
  javascript/package.json
  javascript/src/test/utils/timezone.test.js
Labels: staff-PR

#173 7pm 2 add navbar to storybook
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/stories/components/AppNavbar/AppNavBar.stories.js
  javascript/src/stories/components/Footer/AppFooter.stories.js
Labels: Ready for Staff Review, w21-7pm-2

#168 zm - make google search results all nicely formatted cards
  javascript/src/main/App.css
  javascript/src/main/components/SearchCard/SearchCard.js
  javascript/src/main/components/Utilities/JSONPrettyCard.js
  javascript/src/main/pages/Search/Search.js
  javascript/src/test/pages/Search/Search.test.js
  javascript/src/test/utils/fetch.test.js
Labels: w21-6pm-4

#182 6pm-2: Fix Footer Bug
  javascript/src/main/App.css
Labels: 5, F20-EPIC, w21-6pm-2

#178 6pm 2 message chronological order
  javascript/src/main/components/ChannelMessages/MessageScrollableView.js
  javascript/src/test/components/ChannelMessages/MessageScrollable.test.js
Labels: 10, w21-6pm-2

#186 6pm 2 fixed navbar
  javascript/src/main/App.css
Labels: 5, w21-6pm-2

#169 6pm 2 nicer channel
  javascript/src/main/components/ChannelMessages/MessageScrollableView.js
  javascript/src/test/components/ChannelMessages/MessageScrollable.test.js
Labels: 10, w21-6pm-2

#187 6pm 4 created a Searched Terms page
  javascript/src/main/App.js
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/pages/Admin/SearchedTerms.js
  javascript/src/test/pages/Admin/SearchedTerms.test.js
Labels: FIX ME-Team CR missing, w21-6pm-4

#198 6pm 4 linked the backend of the Searched Terms page to the front end
  javascript/src/main/pages/Admin/SearchedTerms.js
  src/main/java/edu/ucsb/mapache/controllers/SearchedTermsController.java
  src/main/resources/data.sql.sample
  src/test/java/edu/ucsb/mapache/controllers/SearchedTermsControllerTests.java
Labels: w21-6pm-4

#196 6pm 4 google search count
  src/main/java/edu/ucsb/mapache/controllers/SearchController.java
  src/main/java/edu/ucsb/mapache/repositories/SearchRepository.java
  src/test/java/edu/ucsb/mapache/controllers/SearchControllerTests.java
Labels: w21-6pm-4

#180 Team 7pm 2 Create Team Entity and Repository
  src/main/java/edu/ucsb/mapache/controllers/StudentController.java
  src/main/java/edu/ucsb/mapache/entities/Team.java
  src/main/java/edu/ucsb/mapache/repositories/StudentRepository.java
  src/main/java/edu/ucsb/mapache/repositories/TeamRepository.java
  src/test/java/edu/ucsb/mapache/controllers/StudentControllerTests.java
  src/test/java/edu/ucsb/mapache/entities/TeamTests.java
Labels: 20, w21-7pm-2

#179 7pm 2 reformat json slash command
  src/main/java/edu/ucsb/mapache/controllers/SlackSlashCommandController.java
  src/main/java/edu/ucsb/mapache/google/Item.java
  src/main/java/edu/ucsb/mapache/google/Queries.java
  src/main/java/edu/ucsb/mapache/google/RequestItem.java
  src/main/java/edu/ucsb/mapache/google/SearchResult.java
  src/main/java/edu/ucsb/mapache/google/Url.java
  src/test/java/edu/ucsb/mapache/controllers/SlackSlashCommandControllerTests.java
  src/test/java/edu/ucsb/mapache/google/ItemTests.java
  src/test/java/edu/ucsb/mapache/google/QueriesTests.java
  src/test/java/edu/ucsb/mapache/google/RequestItemTests.java
  src/test/java/edu/ucsb/mapache/google/SearchResultTests.java
  src/test/java/edu/ucsb/mapache/google/UrlTests.java
  src/test/java/edu/ucsb/mapache/google/sample.json
Labels: 40, w21-7pm-2

#190 6pm 2 channel name links
  javascript/src/main/components/Channels/ChannelTable.js
  javascript/src/test/components/Channels/ChannelTable.test.js
Labels: Ready for Staff Review, w21-6pm-2

#199 6pm 2 list view
  javascript/src/main/components/ChannelMessages/MessageListView.js
  javascript/src/test/components/ChannelMessages/MessageList.test.js
Labels: 20, TEAM DONE, w21-6pm-2

#181 7pm 2 update admin/teams placeholder
  javascript/src/main/pages/Admin/Teams.js
  src/main/java/edu/ucsb/mapache/controllers/TeamController.java
  src/main/java/edu/ucsb/mapache/entities/Team.java
  src/main/java/edu/ucsb/mapache/repositories/StudentRepository.java
  src/test/java/edu/ucsb/mapache/controllers/TeamControllerTests.java
Labels: 20, TEAM DONE, w21-7pm-2

#200 7pm 2 reformat json slash commandformat
  src/main/java/edu/ucsb/mapache/controllers/SlackSlashCommandController.java
  src/test/java/edu/ucsb/mapache/controllers/SlackSlashCommandControllerTests.java
Labels: FIX ME-Team CR missing, TEAM DONE, w21-7pm-2

#207 Create component
  javascript/src/stories/components/SearchedTermsTable/SearchedTermsTable.stories.js
Labels: Ready for Staff Review
