Repository ucsb-cs156-s21/proj-mapache-search, pull requests merged in 2021-02, with the labels that each got.

#122 AL - Set Actions fetch depth to 2 to fix Codecov reports
  .github/workflows/tests-and-coverage.yml
Labels: staff-PR

#92 pc - make csv uploading user experience better
  javascript/src/main/pages/Students/Students.js
  sample-data/students.csv
  students.csv
Labels: staff-PR

#128 AL - Add bug report issue template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/user-story.md
Labels: staff-PR

#118 6pm 4 fix deprecation in env
  .DS_Store
  javascript/.env
  javascript/jsconfig.json
Labels: w21-6pm-4

#131 added text for instruction on searching emoji
  javascript/src/main/pages/AnalyzeMessageData/AnalyzeReactions.js
  javascript/src/test/pages/AnalyzeMessageData/AnalyzeReactions.test.js
Labels: w21-6pm-4

#132 6pm 4 fix favicon
  javascript/public/android-chrome-192x192.png
  javascript/public/android-chrome-512x512.png
  javascript/public/apple-touch-icon.png
  javascript/public/favicon-16x16.png
  javascript/public/favicon-32x32.png
  javascript/public/favicon.ico
  javascript/public/index.html
  javascript/public/logo192.png
  javascript/public/logo512.png
  javascript/public/manifest.json
Labels: w21-6pm-4

#123 6pm 2 fix footer
  javascript/src/main/components/Footer/AppFooter.js
  javascript/src/test/components/Footer/AppFooter.test.js
Labels: w21-6pm-2

#117 6pm 2 remove profile nav
  javascript/src/main/components/Nav/AppNavbar.js
  javascript/src/main/components/Nav/AuthNav.js
  javascript/src/main/components/Nav/ProfileButton.js
  javascript/src/main/components/Nav/ProfileNav.js
  javascript/src/test/components/Nav/AppNavbar.test.js
  javascript/src/test/components/Nav/AuthNav.test.js
  javascript/src/test/components/Nav/ProfileNav.test.js
Labels: 10, w21-6pm-2

#116 Changed app title from default to "Mapache Search"
  javascript/public/index.html
Labels: w21-6pm-2

#139 6pm 2 sort channels
  javascript/src/main/components/Channels/ChannelTable.js
  javascript/src/test/components/Channels/ChannelTable.test.js
Labels: Ready for Staff Review, w21-6pm-2
